name: multi_validator
description: A starting point for Dart libraries or applications.
version: 1.0.1
repository: https://github.com/alfredoUcar/dart-multi-validator

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
